import pickle

import faiss
import pandas as pd
from sentence_transformers import SentenceTransformer

from app.core.config import FAISS_PATH, PKL_MIN_PATH, SCOPUS_CSV, SCOPUS_SEP

_model_cache = None
_meta_min_cache = None
_index_cache = None
_scopus_cache = None


def load_pkl_and_model(emb_max_seq_len=300):
    global _model_cache, _meta_min_cache
    if _model_cache is not None and _meta_min_cache is not None:
        return _model_cache, _meta_min_cache
    # pkl is a build artifact generated by this repo's own indexing pipeline, not
    # untrusted user input; behavior preserved as-is from the pre-restructure server.py.
    with open(PKL_MIN_PATH, "rb") as f:
        pkl = pickle.load(f)

    meta_min = pkl[
        "meta_min"
    ].copy()  # DataFrame: vec_id, chunk_uid, doc_id, chunk_id, (scopus_id), start/end
    _meta_min_cache = meta_min

    model_name = pkl.get("model", "intfloat/multilingual-e5-small")
    model = SentenceTransformer(model_name, device="cpu")
    model.max_seq_length = min(int(emb_max_seq_len), 512)
    _model_cache = model

    print(f"[INFO] Modelo: {model_name} | max_seq_length={model.max_seq_length}")
    print(f"[INFO] meta_min columnas: {list(meta_min.columns)} | filas={len(meta_min)}")
    return _model_cache, _meta_min_cache


def load_faiss():
    global _index_cache
    if _index_cache is None:
        _index_cache = faiss.read_index(FAISS_PATH)
        print(f"[INFO] Índice FAISS cargado: ntotal={_index_cache.ntotal}")
    return _index_cache


def load_scopus_csv():
    global _scopus_cache
    if _scopus_cache is None:
        df = pd.read_csv(SCOPUS_CSV, sep=SCOPUS_SEP)
        if "scopus_id" not in df.columns:
            raise ValueError(f"{SCOPUS_CSV} no tiene columna 'scopus_id'")
        df["scopus_id"] = df["scopus_id"].astype(str)
        _scopus_cache = df
        print(f"[INFO] scoupusdata.csv: filas={len(df)} | cols={len(df.columns)}")
    return _scopus_cache


def e5_encode_query(model, query_text: str):
    return model.encode(
        [f"query: {query_text}"], normalize_embeddings=True, convert_to_numpy=True
    ).astype("float32")


def search_full_scopus(query_text: str, topk: int = 5) -> pd.DataFrame:
    """
    Une el TOP-K con TODAS las columnas de scoupusdata.csv por scopus_id.
    """
    model, meta_min = load_pkl_and_model()
    index = load_faiss()
    sc = load_scopus_csv()

    q = e5_encode_query(model, query_text)
    D, idx = index.search(q, topk)
    vec_ids = idx[0].tolist()

    hits = meta_min.set_index("vec_id").loc[vec_ids].reset_index()
    hits.insert(1, "score", D[0])

    if "scopus_id" not in hits.columns:
        raise ValueError(
            "meta_min en PKL no contiene 'scopus_id'; no puedo unir con el CSV."
        )

    out = hits.merge(sc, how="left", on="scopus_id")

    # Orden: primero claves/score/offsets, luego TODO el CSV
    front = [
        c
        for c in [
            "vec_id",
            "score",
            "chunk_uid",
            "doc_id",
            "chunk_id",
            "scopus_id",
            "start_token",
            "end_token",
        ]
        if c in out.columns
    ]
    csv_cols = [c for c in sc.columns if c not in front]
    return out[front + csv_cols].reset_index(drop=True)
